# Generated by cucumber-sinatra. (2016-03-23 23:30:45 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/app.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'
#require 'rack_session_access'
require 'byebug'

Capybara.app = BearcatFoodSearch
# Capybara.app.configure do |app|
  # app.use RackSessionAccess::Middleware
# end

class BearcatFoodSearchWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  BearcatFoodSearchWorld.new
end
